### ISSUE TITLE
Why can't I do knex migrate:latest using Docker-Composer?

### ISSUE THREAD

**Issue by davidgatti** [tgriesser/knex#1939]
I have the following `docker-compose.yml` where I'm starting two services:

- postgres
- nodejs app

After the Postgres DB is up I try to run `knex migrate:latest` to create the DB structure. But for some reason the migration keep telling me that is unable to connect. This is strange because:

- I'm able to connect to the DB using Postico and work with the DB no problem.
- The nodejs app is able to connect because I get an error message telling me that the table that I'm trying to select from dose not exists. 
- I'm able to ping the DB container from the Web container

# Question

What am I missing?

# File: docker-compose.yml 

```
version: '2'

services:

  postgres:
    image: "postgres"
    ports:
     - "5433:5432"
    networks:
     - curted
    environment:
     POSTGRES_DB: dbname
     POSTGRES_USER: admin
     POSTGRES_PASSWORD: admin
    volumes:
     - database:/var/lib/postgresql/data

  example.com:
    build: .
    ports:
     - "5000:5000"
    volumes:
     - .:/code
    networks:
     - example
    working_dir: /code
    environment:
     DATABASE_URL: postgres://admin:admin@172.18.0.2:5433/dbname
     NODE_ENV: local
    command: bash -c "sleep 10 && npm run knex migrate:latest --file knexfile.js"
    depends_on:
     - postgres

networks:
  curted:
    driver: bridge

volumes:
  database:
```

# The knexfile.js

```
module.exports = {
	local: {
		client: 'pg',
		connection: process.env.DATABASE_URL,
		ssl: false,
		migrations: {
			tableName: 'knex_migrations'
		}
	},
	staging: {
		client: 'pg',
		connection: process.env.DATABASE_URL,
		ssl: true,
		migrations: {
			tableName: 'knex_migrations'
		},
		pool: {
			min: 1,
			max: 2
		}
	},
	production: {
		client: 'pg',
		connection: process.env.DATABASE_URL,
		ssl: true,
		migrations: {
			tableName: 'knex_migrations'
		},
		pool: {
			min: 1,
			max: 2
		}
	}
};
```

# Erro Message

```
curted.com_1  | > CuratedProducts@1.0.0 knex /home/app
curted.com_1  | > knex "migrate:latest"
curted.com_1  |
curted.com_1  | Using environment: local
curted.com_1  | Error: connect ECONNREFUSED 172.18.0.2:5433
curted.com_1  |     at Object.exports._errnoException (util.js:1022:11)
curted.com_1  |     at exports._exceptionWithHostPort (util.js:1045:20)
curted.com_1  |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
```

**Comment by davidgatti** [comment]
Anyone? 😢

**Comment by elhigu** [comment]
Probably some docker people can help you more than knex devs. 

I'll close this since this is not really a knex issue, but just how to work with containers and how to configure postgres.

If someone actually knows what is this about please answer though.

**Comment by davidgatti** [comment]
@elhigu how are you so sure that this is not an issue with knex? ;) because as mentioned above, I'm able to connect to the DB with multiple ways, even keno can connect at a App level. But the migration acting in a strange way.

ps. is it possible to output what Env variables the migration code sees? Because I'm starting to think that the problem might be here. Just a thought.

**Comment by elhigu** [comment]
@davidgatti you should be able to do `console.dir(process.env)`. 

I'm sure that this is not knex problem, because people are running migrations just fine in simpler configuration (without containers and local or remote db server).

Try to make your configuration to work first in simpler setup to make sure that you are using knex correctly and have configured postgres correctly.

**Comment by davidgatti** [comment]
If I have `npm run knex migrate:latest --file knexfile.js` you mean to put `console.dir(process.env)` inside `knexfile.js`?

About the simpler configuration, I see you didn't take the time to read the issue that I wrote, sadness 😥. In this issue I try to explain the following:

- I posted my `knexfile.js` to show what I have
- the `knexfile.js` and knex itself as a module working inside the NodeJS app, as explained in the 2nd point on top of this issue 
- and on my local machine my project works no problem, I can migrate left and right no problem. 

I did everything to reach a point where the Issue seems to be focused on the migration aspect of knex. Thus my assumption that the problem is not with docker, but rather with knex which might read some data in the wrong way based on the different environment.

Of course I might be wrong, but dismissing this issue seams to me to be bit odd, because I believe that there is something going on based on all the proof that I have provided. 

# To make sure I'm not a lunatic

If in the app I have the env variable `DATABASE_URL` set the same as in the docker-compose, and run the migration the same way I do it on my local machine. I would expect the same result. 

Based on my observation the migration part is just doing something different.

If you don't care about this weird behavior, then sure I can pick another ORM and no harm feelings.

**Comment by elhigu** [comment]
I did read the issue and nothing did seem like the problem would be caused by bug in knex. 

That is the reason why I closed the issue. If there is some proofs that problem is caused by bug and can be reproduced without docker setup it could be left to be open.

You may add that console.dir for example to a migration file. You can also add debug prints to a knex source code under node_modules if you are determined to debug why your setup doesnt work.

**Comment by davidgatti** [comment]
OK. I'll dig deeper, and will let you know.

**Comment by mjhea0** [comment]
@davidgatti did you figure this out? I'm getting the same error.

**Comment by davidgatti** [comment]
@mjhea0 Sorry didn't have time to go back to this, to much work :( I'll probably spend next weekend figuring this out.

**Comment by mjhea0** [comment]
@davidgatti email me if you want to hack together. I am going to try this: https://github.com/tgriesser/knex/issues/1843#issuecomment-284877449

**Comment by sonycamera** [comment]
@davidgatti 
I have the same issue and resolve it by following code:
```
echo "Running migrations ..."
for i in $(seq 1 30); do
    knex migrate:latest
    [ $? = 0 ] && break
    echo "Reconnecting db ..." && sleep 1
done
```

Below are some logs:
```
Running migrations ...
Using environment: production
Error: connect ECONNREFUSED 172.19.0.3:5432
    at Object.exports._errnoException (util.js:953:11)
    at exports._exceptionWithHostPort (util.js:976:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
Reconnecting kdb ...
Using environment: production
Error: connect ECONNREFUSED 172.19.0.3:5432
    at Object.exports._errnoException (util.js:953:11)
    at exports._exceptionWithHostPort (util.js:976:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
Reconnecting kdb ...
Using environment: production
error: the database system is starting up
    at Connection.parseE (/opt/xxx/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/opt/xxx/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/opt/xxx/node_modules/pg/lib/connection.js:105:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at Socket.Readable.push (_stream_readable.js:130:10)
    at TCP.onread (net.js:542:20)
Reconnecting kdb ...
Using environment: production
Already up to date

```

The logs show that DB is not ready in the first three connecting tries. So if we run knex migration just one time, it will be failed in most cases. But I do set timeout parameters (acquireTimeout & bailAfter) in knexfile.js like this:
```
  production: {
    client: 'pg',
    connection: {
      host: 'dbserver',
      database: mydb,
      user:     myuser,
      password: mypwd
    },
    pool: {
      min: 2,
      max: 10,
      acquireTimeout: 30*1000,
      bailAfter: 30*1000
    },
    migrations: {
      tableName: 'knex_migrations'
    }
  },
```
I expect that knex will keep trying to connect DB in 30 seconds. But it's not. 
Is this a knex bug? or 
Is there any other proper parameter can control the timeout/retrying?

**Comment by Bram-Zijp** [comment]
I was running the migrate commands from my terminal instead of from inside the docker container.
When I ran the migration from within the container which is hosting the node.js app it migrated fine.

I use this in my knexfile.js as connection:
```
      connection: {
            host: 'db',
            database: 'cms',
            user: 'cms',
            password: 'test',
        },
```

this is my docker-compose.yml
```
version: '2'
services:
  web:
    build: .
    ports:
      - 3001:3001
    depends_on:
      - db
    links:
      - db
  db:
    image: postgres:10
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: cms
      POSTGRES_USER: cms
      POSTGRES_PASSWORD: test

```


`docker exec CONTAINER_NAME sh -c "npm run migrate"`
The migrate script in my package.json looks like this:
`"migrate": "knex migrate:rollback && knex migrate:latest && knex seed:run",`


Hope this helps those who are struggling.

**Comment by vulgur** [comment]
I got the same issue. Migration is fine by running `knex migrate:latest` outside the web container while the db container is running, but always fails by the erro of "connect ECONNREFUSED".

**Comment by vulgur** [comment]
Hey guys, I found the reason and the solution. The solution is generally speaking the same as @Bram-Zijp . Here is my knexfile.js: 
```
module.exports = {

  development: {
    client: 'mysql2',
      debug:true,
    connection: {
        host:'docker-mysql',
        user: 'root',
        password: '1qaz',
        port: '',
        database: 'docker_db'
    },
      migrations: {
          tableName: 'knex_migrations'
      }
  },
};
```
The key is to set `host` with the name of the db service in docker-compose. Setting `port` to empty string or 3306 both will okay ( I don't know why but it works). 

The ECONNREFUSED error means the web app cannot connect the db, and I've tried many hosts and ports but all the tries failed, like `localhost:3306` and `0.0.0.0:13306` and so on. The reason is the `localhost:3306` actually refers the container itself, not the docker host. 

Plus, make sure the migration is executed after db fully initializing.

**Comment by sscovil** [comment]
A little late to the party, but I thought I'd share a Node script that I run when using docker-compose with a Knex migration service.

```js
"use strict";

const config = require("./knexfile");
const Knex = require("knex");

const knex = Knex(config);

async function runMigrations(retries, delay) {
  for (let i = 1; i !== retries; i++) {
    try {
      return await knex.migrate.latest();
    } catch (err) {
      await setTimeoutAsync(delay * i);
    }
  }

  throw new Error(`Unable to run migrations after ${retries} attempts.`);
}

function setTimeoutAsync(ms) {
  return new Promise(resolve => {
    setTimeout(resolve, ms);
  });
}

runMigrations(10, 500)
  .catch(err => {
    console.log(err);
    process.exit(1);
  })
  .then(res => {
    console.log(`Batch ${res[0]} run: ${res[1].length} migrations`);
    console.log(res[1].join("\n"));
    process.exit();
  });
```

This is in a directory called `db` off of the root directory of my project. The `docker-compose.yml` file looks like this:

```yaml
version: "3.7"

services:
  postgres:
    environment:
      - POSTGRES_DB=mydb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"
    image: postgres:9.6
    restart: always
    volumes:
      - ".:/data"

  migrations:
    build: ./db
    depends_on:
      - postgres
    command: bash -c "npm start"
    environment:
      - DOCKER=true
      - NODE_ENV=development
      - PGHOST=postgres
      - PGPORT=5432
      - PGUSER=postgres
      - PGPASSWORD=
      - PGDATABASE=mydb
    volumes:
      - "./db:/db"
```
