### ISSUE TITLE
Running knex migrations on AWS ElasticBeanStalk

### ISSUE THREAD

**Issue by gmcdowell** [tgriesser/knex#678]
Hi All,

Just wonder if anyone has solved this one. Challenges faced include access to global knex & node modules among others.

Any suggestions/snippets appreciated.

**Comment by bendrucker** [comment]
Closing this because it's not knex specific. Stack Overflow may be a better place to get an answer. If you or someone else figures out a solution certain post it or link to it here.

**Comment by TehNrd** [comment]
@gmcdowell Ever make any progress on this? We are currently evaluation Elastic Beanstalk.

**Comment by gmcdowell** [comment]
Yup. You need to install knex globally e.g.
sudo /opt/elasticbeanstalk/node-install/node-v0.10.31-linux-x64/bin/npm install -g knex

**Comment by TehNrd** [comment]
Thanks. If anyone else comes across this you can probably accomplish this with [container commands](http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/customize-containers-ec2.html#customize-containers-format-container_commands). Disclaimer I haven't actually tried the script below but it should work:

```
{
	"container_commands":{
		"01_enable_rootaccess":{
			"command": "echo Defaults:root \!requiretty >> /etc/sudoers",
		},
		"02_install_knex":{
			"command": "sudo /opt/elasticbeanstalk/node-install/node-v0.12.0-linux-x64/bin/npm install -g knex",
			"leader_only": true
		}
		"03_database_migrations":{
			"command": "knex migrate:latest",
			"leader_only": true
		}
	}
}
```

**Comment by misaxi** [comment]
I got it working with local knex package install

**Comment by jschr** [comment]
Since this is the top hit on google, posting my working setup:

.ebextensions/01-migrate-db.config
```
container_commands:
  01_node_binary:
    command: "ln -sf `ls -td /opt/elasticbeanstalk/node-install/node-* | head -1`/bin/node /bin/node"
    leader_only: true
  02_npm_binary:
    command: "ln -sf `ls -td /opt/elasticbeanstalk/node-install/node-* | head -1`/bin/npm /bin/npm"
    leader_only: true
  03_migrate_db:
    command: "sudo DB_HOST=${DB_HOST} DB_PORT=${DB_PORT} DB_NAME=${DB_NAME} DB_USER=${DB_USER} DB_PASSWORD=${DB_PASSWORD} npm run db:migration:run"
    leader_only: true
```

package.json
```
{
   scripts: {
     "db:migration:run": "knex migrate:latest"
   }
}
```

http://stackoverflow.com/questions/32082115/running-knex-migrations-on-elastic-beanstalk
